#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4F{1,0,7.2,1
#
release.xm4fg: package/cfg/release.xm4fg.mak

clean::
	-$(RM) package/cfg/release.xm4fg.mak
