################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../fonts/fontcm12.c \
../fonts/fontcm12b.c \
../fonts/fontcm12i.c \
../fonts/fontcm14.c \
../fonts/fontcm14b.c \
../fonts/fontcm14i.c \
../fonts/fontcm16.c \
../fonts/fontcm16b.c \
../fonts/fontcm16i.c \
../fonts/fontcm18.c \
../fonts/fontcm18b.c \
../fonts/fontcm18i.c \
../fonts/fontcm20.c \
../fonts/fontcm20b.c \
../fonts/fontcm20i.c \
../fonts/fontcm22.c \
../fonts/fontcm22b.c \
../fonts/fontcm22i.c \
../fonts/fontcm24.c \
../fonts/fontcm24b.c \
../fonts/fontcm24i.c \
../fonts/fontcm26.c \
../fonts/fontcm26b.c \
../fonts/fontcm26i.c \
../fonts/fontcm28.c \
../fonts/fontcm28b.c \
../fonts/fontcm28i.c \
../fonts/fontcm30.c \
../fonts/fontcm30b.c \
../fonts/fontcm30i.c \
../fonts/fontcm32.c \
../fonts/fontcm32b.c \
../fonts/fontcm32i.c \
../fonts/fontcm34.c \
../fonts/fontcm34b.c \
../fonts/fontcm34i.c \
../fonts/fontcm36.c \
../fonts/fontcm36b.c \
../fonts/fontcm36i.c \
../fonts/fontcm38.c \
../fonts/fontcm38b.c \
../fonts/fontcm38i.c \
../fonts/fontcm40.c \
../fonts/fontcm40b.c \
../fonts/fontcm40i.c \
../fonts/fontcm42.c \
../fonts/fontcm42b.c \
../fonts/fontcm42i.c \
../fonts/fontcm44.c \
../fonts/fontcm44b.c \
../fonts/fontcm44i.c \
../fonts/fontcm46.c \
../fonts/fontcm46b.c \
../fonts/fontcm46i.c \
../fonts/fontcm48.c \
../fonts/fontcm48b.c \
../fonts/fontcm48i.c \
../fonts/fontcmsc12.c \
../fonts/fontcmsc14.c \
../fonts/fontcmsc16.c \
../fonts/fontcmsc18.c \
../fonts/fontcmsc20.c \
../fonts/fontcmsc22.c \
../fonts/fontcmsc24.c \
../fonts/fontcmsc26.c \
../fonts/fontcmsc28.c \
../fonts/fontcmsc30.c \
../fonts/fontcmsc32.c \
../fonts/fontcmsc34.c \
../fonts/fontcmsc36.c \
../fonts/fontcmsc38.c \
../fonts/fontcmsc40.c \
../fonts/fontcmsc42.c \
../fonts/fontcmsc44.c \
../fonts/fontcmsc46.c \
../fonts/fontcmsc48.c \
../fonts/fontcmss12.c \
../fonts/fontcmss12b.c \
../fonts/fontcmss12i.c \
../fonts/fontcmss14.c \
../fonts/fontcmss14b.c \
../fonts/fontcmss14i.c \
../fonts/fontcmss16.c \
../fonts/fontcmss16b.c \
../fonts/fontcmss16i.c \
../fonts/fontcmss18.c \
../fonts/fontcmss18b.c \
../fonts/fontcmss18i.c \
../fonts/fontcmss20.c \
../fonts/fontcmss20b.c \
../fonts/fontcmss20i.c \
../fonts/fontcmss22.c \
../fonts/fontcmss22b.c \
../fonts/fontcmss22i.c \
../fonts/fontcmss24.c \
../fonts/fontcmss24b.c \
../fonts/fontcmss24i.c \
../fonts/fontcmss26.c \
../fonts/fontcmss26b.c \
../fonts/fontcmss26i.c \
../fonts/fontcmss28.c \
../fonts/fontcmss28b.c \
../fonts/fontcmss28i.c \
../fonts/fontcmss30.c \
../fonts/fontcmss30b.c \
../fonts/fontcmss30i.c \
../fonts/fontcmss32.c \
../fonts/fontcmss32b.c \
../fonts/fontcmss32i.c \
../fonts/fontcmss34.c \
../fonts/fontcmss34b.c \
../fonts/fontcmss34i.c \
../fonts/fontcmss36.c \
../fonts/fontcmss36b.c \
../fonts/fontcmss36i.c \
../fonts/fontcmss38.c \
../fonts/fontcmss38b.c \
../fonts/fontcmss38i.c \
../fonts/fontcmss40.c \
../fonts/fontcmss40b.c \
../fonts/fontcmss40i.c \
../fonts/fontcmss42.c \
../fonts/fontcmss42b.c \
../fonts/fontcmss42i.c \
../fonts/fontcmss44.c \
../fonts/fontcmss44b.c \
../fonts/fontcmss44i.c \
../fonts/fontcmss46.c \
../fonts/fontcmss46b.c \
../fonts/fontcmss46i.c \
../fonts/fontcmss48.c \
../fonts/fontcmss48b.c \
../fonts/fontcmss48i.c \
../fonts/fontcmtt12.c \
../fonts/fontcmtt14.c \
../fonts/fontcmtt16.c \
../fonts/fontcmtt18.c \
../fonts/fontcmtt20.c \
../fonts/fontcmtt22.c \
../fonts/fontcmtt24.c \
../fonts/fontcmtt26.c \
../fonts/fontcmtt28.c \
../fonts/fontcmtt30.c \
../fonts/fontcmtt32.c \
../fonts/fontcmtt34.c \
../fonts/fontcmtt36.c \
../fonts/fontcmtt38.c \
../fonts/fontcmtt40.c \
../fonts/fontcmtt42.c \
../fonts/fontcmtt44.c \
../fonts/fontcmtt46.c \
../fonts/fontcmtt48.c \
../fonts/fontfixed6x8.c 

C_DEPS += \
./fonts/fontcm12.d \
./fonts/fontcm12b.d \
./fonts/fontcm12i.d \
./fonts/fontcm14.d \
./fonts/fontcm14b.d \
./fonts/fontcm14i.d \
./fonts/fontcm16.d \
./fonts/fontcm16b.d \
./fonts/fontcm16i.d \
./fonts/fontcm18.d \
./fonts/fontcm18b.d \
./fonts/fontcm18i.d \
./fonts/fontcm20.d \
./fonts/fontcm20b.d \
./fonts/fontcm20i.d \
./fonts/fontcm22.d \
./fonts/fontcm22b.d \
./fonts/fontcm22i.d \
./fonts/fontcm24.d \
./fonts/fontcm24b.d \
./fonts/fontcm24i.d \
./fonts/fontcm26.d \
./fonts/fontcm26b.d \
./fonts/fontcm26i.d \
./fonts/fontcm28.d \
./fonts/fontcm28b.d \
./fonts/fontcm28i.d \
./fonts/fontcm30.d \
./fonts/fontcm30b.d \
./fonts/fontcm30i.d \
./fonts/fontcm32.d \
./fonts/fontcm32b.d \
./fonts/fontcm32i.d \
./fonts/fontcm34.d \
./fonts/fontcm34b.d \
./fonts/fontcm34i.d \
./fonts/fontcm36.d \
./fonts/fontcm36b.d \
./fonts/fontcm36i.d \
./fonts/fontcm38.d \
./fonts/fontcm38b.d \
./fonts/fontcm38i.d \
./fonts/fontcm40.d \
./fonts/fontcm40b.d \
./fonts/fontcm40i.d \
./fonts/fontcm42.d \
./fonts/fontcm42b.d \
./fonts/fontcm42i.d \
./fonts/fontcm44.d \
./fonts/fontcm44b.d \
./fonts/fontcm44i.d \
./fonts/fontcm46.d \
./fonts/fontcm46b.d \
./fonts/fontcm46i.d \
./fonts/fontcm48.d \
./fonts/fontcm48b.d \
./fonts/fontcm48i.d \
./fonts/fontcmsc12.d \
./fonts/fontcmsc14.d \
./fonts/fontcmsc16.d \
./fonts/fontcmsc18.d \
./fonts/fontcmsc20.d \
./fonts/fontcmsc22.d \
./fonts/fontcmsc24.d \
./fonts/fontcmsc26.d \
./fonts/fontcmsc28.d \
./fonts/fontcmsc30.d \
./fonts/fontcmsc32.d \
./fonts/fontcmsc34.d \
./fonts/fontcmsc36.d \
./fonts/fontcmsc38.d \
./fonts/fontcmsc40.d \
./fonts/fontcmsc42.d \
./fonts/fontcmsc44.d \
./fonts/fontcmsc46.d \
./fonts/fontcmsc48.d \
./fonts/fontcmss12.d \
./fonts/fontcmss12b.d \
./fonts/fontcmss12i.d \
./fonts/fontcmss14.d \
./fonts/fontcmss14b.d \
./fonts/fontcmss14i.d \
./fonts/fontcmss16.d \
./fonts/fontcmss16b.d \
./fonts/fontcmss16i.d \
./fonts/fontcmss18.d \
./fonts/fontcmss18b.d \
./fonts/fontcmss18i.d \
./fonts/fontcmss20.d \
./fonts/fontcmss20b.d \
./fonts/fontcmss20i.d \
./fonts/fontcmss22.d \
./fonts/fontcmss22b.d \
./fonts/fontcmss22i.d \
./fonts/fontcmss24.d \
./fonts/fontcmss24b.d \
./fonts/fontcmss24i.d \
./fonts/fontcmss26.d \
./fonts/fontcmss26b.d \
./fonts/fontcmss26i.d \
./fonts/fontcmss28.d \
./fonts/fontcmss28b.d \
./fonts/fontcmss28i.d \
./fonts/fontcmss30.d \
./fonts/fontcmss30b.d \
./fonts/fontcmss30i.d \
./fonts/fontcmss32.d \
./fonts/fontcmss32b.d \
./fonts/fontcmss32i.d \
./fonts/fontcmss34.d \
./fonts/fontcmss34b.d \
./fonts/fontcmss34i.d \
./fonts/fontcmss36.d \
./fonts/fontcmss36b.d \
./fonts/fontcmss36i.d \
./fonts/fontcmss38.d \
./fonts/fontcmss38b.d \
./fonts/fontcmss38i.d \
./fonts/fontcmss40.d \
./fonts/fontcmss40b.d \
./fonts/fontcmss40i.d \
./fonts/fontcmss42.d \
./fonts/fontcmss42b.d \
./fonts/fontcmss42i.d \
./fonts/fontcmss44.d \
./fonts/fontcmss44b.d \
./fonts/fontcmss44i.d \
./fonts/fontcmss46.d \
./fonts/fontcmss46b.d \
./fonts/fontcmss46i.d \
./fonts/fontcmss48.d \
./fonts/fontcmss48b.d \
./fonts/fontcmss48i.d \
./fonts/fontcmtt12.d \
./fonts/fontcmtt14.d \
./fonts/fontcmtt16.d \
./fonts/fontcmtt18.d \
./fonts/fontcmtt20.d \
./fonts/fontcmtt22.d \
./fonts/fontcmtt24.d \
./fonts/fontcmtt26.d \
./fonts/fontcmtt28.d \
./fonts/fontcmtt30.d \
./fonts/fontcmtt32.d \
./fonts/fontcmtt34.d \
./fonts/fontcmtt36.d \
./fonts/fontcmtt38.d \
./fonts/fontcmtt40.d \
./fonts/fontcmtt42.d \
./fonts/fontcmtt44.d \
./fonts/fontcmtt46.d \
./fonts/fontcmtt48.d \
./fonts/fontfixed6x8.d 

OBJS += \
./fonts/fontcm12.o \
./fonts/fontcm12b.o \
./fonts/fontcm12i.o \
./fonts/fontcm14.o \
./fonts/fontcm14b.o \
./fonts/fontcm14i.o \
./fonts/fontcm16.o \
./fonts/fontcm16b.o \
./fonts/fontcm16i.o \
./fonts/fontcm18.o \
./fonts/fontcm18b.o \
./fonts/fontcm18i.o \
./fonts/fontcm20.o \
./fonts/fontcm20b.o \
./fonts/fontcm20i.o \
./fonts/fontcm22.o \
./fonts/fontcm22b.o \
./fonts/fontcm22i.o \
./fonts/fontcm24.o \
./fonts/fontcm24b.o \
./fonts/fontcm24i.o \
./fonts/fontcm26.o \
./fonts/fontcm26b.o \
./fonts/fontcm26i.o \
./fonts/fontcm28.o \
./fonts/fontcm28b.o \
./fonts/fontcm28i.o \
./fonts/fontcm30.o \
./fonts/fontcm30b.o \
./fonts/fontcm30i.o \
./fonts/fontcm32.o \
./fonts/fontcm32b.o \
./fonts/fontcm32i.o \
./fonts/fontcm34.o \
./fonts/fontcm34b.o \
./fonts/fontcm34i.o \
./fonts/fontcm36.o \
./fonts/fontcm36b.o \
./fonts/fontcm36i.o \
./fonts/fontcm38.o \
./fonts/fontcm38b.o \
./fonts/fontcm38i.o \
./fonts/fontcm40.o \
./fonts/fontcm40b.o \
./fonts/fontcm40i.o \
./fonts/fontcm42.o \
./fonts/fontcm42b.o \
./fonts/fontcm42i.o \
./fonts/fontcm44.o \
./fonts/fontcm44b.o \
./fonts/fontcm44i.o \
./fonts/fontcm46.o \
./fonts/fontcm46b.o \
./fonts/fontcm46i.o \
./fonts/fontcm48.o \
./fonts/fontcm48b.o \
./fonts/fontcm48i.o \
./fonts/fontcmsc12.o \
./fonts/fontcmsc14.o \
./fonts/fontcmsc16.o \
./fonts/fontcmsc18.o \
./fonts/fontcmsc20.o \
./fonts/fontcmsc22.o \
./fonts/fontcmsc24.o \
./fonts/fontcmsc26.o \
./fonts/fontcmsc28.o \
./fonts/fontcmsc30.o \
./fonts/fontcmsc32.o \
./fonts/fontcmsc34.o \
./fonts/fontcmsc36.o \
./fonts/fontcmsc38.o \
./fonts/fontcmsc40.o \
./fonts/fontcmsc42.o \
./fonts/fontcmsc44.o \
./fonts/fontcmsc46.o \
./fonts/fontcmsc48.o \
./fonts/fontcmss12.o \
./fonts/fontcmss12b.o \
./fonts/fontcmss12i.o \
./fonts/fontcmss14.o \
./fonts/fontcmss14b.o \
./fonts/fontcmss14i.o \
./fonts/fontcmss16.o \
./fonts/fontcmss16b.o \
./fonts/fontcmss16i.o \
./fonts/fontcmss18.o \
./fonts/fontcmss18b.o \
./fonts/fontcmss18i.o \
./fonts/fontcmss20.o \
./fonts/fontcmss20b.o \
./fonts/fontcmss20i.o \
./fonts/fontcmss22.o \
./fonts/fontcmss22b.o \
./fonts/fontcmss22i.o \
./fonts/fontcmss24.o \
./fonts/fontcmss24b.o \
./fonts/fontcmss24i.o \
./fonts/fontcmss26.o \
./fonts/fontcmss26b.o \
./fonts/fontcmss26i.o \
./fonts/fontcmss28.o \
./fonts/fontcmss28b.o \
./fonts/fontcmss28i.o \
./fonts/fontcmss30.o \
./fonts/fontcmss30b.o \
./fonts/fontcmss30i.o \
./fonts/fontcmss32.o \
./fonts/fontcmss32b.o \
./fonts/fontcmss32i.o \
./fonts/fontcmss34.o \
./fonts/fontcmss34b.o \
./fonts/fontcmss34i.o \
./fonts/fontcmss36.o \
./fonts/fontcmss36b.o \
./fonts/fontcmss36i.o \
./fonts/fontcmss38.o \
./fonts/fontcmss38b.o \
./fonts/fontcmss38i.o \
./fonts/fontcmss40.o \
./fonts/fontcmss40b.o \
./fonts/fontcmss40i.o \
./fonts/fontcmss42.o \
./fonts/fontcmss42b.o \
./fonts/fontcmss42i.o \
./fonts/fontcmss44.o \
./fonts/fontcmss44b.o \
./fonts/fontcmss44i.o \
./fonts/fontcmss46.o \
./fonts/fontcmss46b.o \
./fonts/fontcmss46i.o \
./fonts/fontcmss48.o \
./fonts/fontcmss48b.o \
./fonts/fontcmss48i.o \
./fonts/fontcmtt12.o \
./fonts/fontcmtt14.o \
./fonts/fontcmtt16.o \
./fonts/fontcmtt18.o \
./fonts/fontcmtt20.o \
./fonts/fontcmtt22.o \
./fonts/fontcmtt24.o \
./fonts/fontcmtt26.o \
./fonts/fontcmtt28.o \
./fonts/fontcmtt30.o \
./fonts/fontcmtt32.o \
./fonts/fontcmtt34.o \
./fonts/fontcmtt36.o \
./fonts/fontcmtt38.o \
./fonts/fontcmtt40.o \
./fonts/fontcmtt42.o \
./fonts/fontcmtt44.o \
./fonts/fontcmtt46.o \
./fonts/fontcmtt48.o \
./fonts/fontfixed6x8.o 

OBJS__QUOTED += \
"fonts\fontcm12.o" \
"fonts\fontcm12b.o" \
"fonts\fontcm12i.o" \
"fonts\fontcm14.o" \
"fonts\fontcm14b.o" \
"fonts\fontcm14i.o" \
"fonts\fontcm16.o" \
"fonts\fontcm16b.o" \
"fonts\fontcm16i.o" \
"fonts\fontcm18.o" \
"fonts\fontcm18b.o" \
"fonts\fontcm18i.o" \
"fonts\fontcm20.o" \
"fonts\fontcm20b.o" \
"fonts\fontcm20i.o" \
"fonts\fontcm22.o" \
"fonts\fontcm22b.o" \
"fonts\fontcm22i.o" \
"fonts\fontcm24.o" \
"fonts\fontcm24b.o" \
"fonts\fontcm24i.o" \
"fonts\fontcm26.o" \
"fonts\fontcm26b.o" \
"fonts\fontcm26i.o" \
"fonts\fontcm28.o" \
"fonts\fontcm28b.o" \
"fonts\fontcm28i.o" \
"fonts\fontcm30.o" \
"fonts\fontcm30b.o" \
"fonts\fontcm30i.o" \
"fonts\fontcm32.o" \
"fonts\fontcm32b.o" \
"fonts\fontcm32i.o" \
"fonts\fontcm34.o" \
"fonts\fontcm34b.o" \
"fonts\fontcm34i.o" \
"fonts\fontcm36.o" \
"fonts\fontcm36b.o" \
"fonts\fontcm36i.o" \
"fonts\fontcm38.o" \
"fonts\fontcm38b.o" \
"fonts\fontcm38i.o" \
"fonts\fontcm40.o" \
"fonts\fontcm40b.o" \
"fonts\fontcm40i.o" \
"fonts\fontcm42.o" \
"fonts\fontcm42b.o" \
"fonts\fontcm42i.o" \
"fonts\fontcm44.o" \
"fonts\fontcm44b.o" \
"fonts\fontcm44i.o" \
"fonts\fontcm46.o" \
"fonts\fontcm46b.o" \
"fonts\fontcm46i.o" \
"fonts\fontcm48.o" \
"fonts\fontcm48b.o" \
"fonts\fontcm48i.o" \
"fonts\fontcmsc12.o" \
"fonts\fontcmsc14.o" \
"fonts\fontcmsc16.o" \
"fonts\fontcmsc18.o" \
"fonts\fontcmsc20.o" \
"fonts\fontcmsc22.o" \
"fonts\fontcmsc24.o" \
"fonts\fontcmsc26.o" \
"fonts\fontcmsc28.o" \
"fonts\fontcmsc30.o" \
"fonts\fontcmsc32.o" \
"fonts\fontcmsc34.o" \
"fonts\fontcmsc36.o" \
"fonts\fontcmsc38.o" \
"fonts\fontcmsc40.o" \
"fonts\fontcmsc42.o" \
"fonts\fontcmsc44.o" \
"fonts\fontcmsc46.o" \
"fonts\fontcmsc48.o" \
"fonts\fontcmss12.o" \
"fonts\fontcmss12b.o" \
"fonts\fontcmss12i.o" \
"fonts\fontcmss14.o" \
"fonts\fontcmss14b.o" \
"fonts\fontcmss14i.o" \
"fonts\fontcmss16.o" \
"fonts\fontcmss16b.o" \
"fonts\fontcmss16i.o" \
"fonts\fontcmss18.o" \
"fonts\fontcmss18b.o" \
"fonts\fontcmss18i.o" \
"fonts\fontcmss20.o" \
"fonts\fontcmss20b.o" \
"fonts\fontcmss20i.o" \
"fonts\fontcmss22.o" \
"fonts\fontcmss22b.o" \
"fonts\fontcmss22i.o" \
"fonts\fontcmss24.o" \
"fonts\fontcmss24b.o" \
"fonts\fontcmss24i.o" \
"fonts\fontcmss26.o" \
"fonts\fontcmss26b.o" \
"fonts\fontcmss26i.o" \
"fonts\fontcmss28.o" \
"fonts\fontcmss28b.o" \
"fonts\fontcmss28i.o" \
"fonts\fontcmss30.o" \
"fonts\fontcmss30b.o" \
"fonts\fontcmss30i.o" \
"fonts\fontcmss32.o" \
"fonts\fontcmss32b.o" \
"fonts\fontcmss32i.o" \
"fonts\fontcmss34.o" \
"fonts\fontcmss34b.o" \
"fonts\fontcmss34i.o" \
"fonts\fontcmss36.o" \
"fonts\fontcmss36b.o" \
"fonts\fontcmss36i.o" \
"fonts\fontcmss38.o" \
"fonts\fontcmss38b.o" \
"fonts\fontcmss38i.o" \
"fonts\fontcmss40.o" \
"fonts\fontcmss40b.o" \
"fonts\fontcmss40i.o" \
"fonts\fontcmss42.o" \
"fonts\fontcmss42b.o" \
"fonts\fontcmss42i.o" \
"fonts\fontcmss44.o" \
"fonts\fontcmss44b.o" \
"fonts\fontcmss44i.o" \
"fonts\fontcmss46.o" \
"fonts\fontcmss46b.o" \
"fonts\fontcmss46i.o" \
"fonts\fontcmss48.o" \
"fonts\fontcmss48b.o" \
"fonts\fontcmss48i.o" \
"fonts\fontcmtt12.o" \
"fonts\fontcmtt14.o" \
"fonts\fontcmtt16.o" \
"fonts\fontcmtt18.o" \
"fonts\fontcmtt20.o" \
"fonts\fontcmtt22.o" \
"fonts\fontcmtt24.o" \
"fonts\fontcmtt26.o" \
"fonts\fontcmtt28.o" \
"fonts\fontcmtt30.o" \
"fonts\fontcmtt32.o" \
"fonts\fontcmtt34.o" \
"fonts\fontcmtt36.o" \
"fonts\fontcmtt38.o" \
"fonts\fontcmtt40.o" \
"fonts\fontcmtt42.o" \
"fonts\fontcmtt44.o" \
"fonts\fontcmtt46.o" \
"fonts\fontcmtt48.o" \
"fonts\fontfixed6x8.o" 

C_DEPS__QUOTED += \
"fonts\fontcm12.d" \
"fonts\fontcm12b.d" \
"fonts\fontcm12i.d" \
"fonts\fontcm14.d" \
"fonts\fontcm14b.d" \
"fonts\fontcm14i.d" \
"fonts\fontcm16.d" \
"fonts\fontcm16b.d" \
"fonts\fontcm16i.d" \
"fonts\fontcm18.d" \
"fonts\fontcm18b.d" \
"fonts\fontcm18i.d" \
"fonts\fontcm20.d" \
"fonts\fontcm20b.d" \
"fonts\fontcm20i.d" \
"fonts\fontcm22.d" \
"fonts\fontcm22b.d" \
"fonts\fontcm22i.d" \
"fonts\fontcm24.d" \
"fonts\fontcm24b.d" \
"fonts\fontcm24i.d" \
"fonts\fontcm26.d" \
"fonts\fontcm26b.d" \
"fonts\fontcm26i.d" \
"fonts\fontcm28.d" \
"fonts\fontcm28b.d" \
"fonts\fontcm28i.d" \
"fonts\fontcm30.d" \
"fonts\fontcm30b.d" \
"fonts\fontcm30i.d" \
"fonts\fontcm32.d" \
"fonts\fontcm32b.d" \
"fonts\fontcm32i.d" \
"fonts\fontcm34.d" \
"fonts\fontcm34b.d" \
"fonts\fontcm34i.d" \
"fonts\fontcm36.d" \
"fonts\fontcm36b.d" \
"fonts\fontcm36i.d" \
"fonts\fontcm38.d" \
"fonts\fontcm38b.d" \
"fonts\fontcm38i.d" \
"fonts\fontcm40.d" \
"fonts\fontcm40b.d" \
"fonts\fontcm40i.d" \
"fonts\fontcm42.d" \
"fonts\fontcm42b.d" \
"fonts\fontcm42i.d" \
"fonts\fontcm44.d" \
"fonts\fontcm44b.d" \
"fonts\fontcm44i.d" \
"fonts\fontcm46.d" \
"fonts\fontcm46b.d" \
"fonts\fontcm46i.d" \
"fonts\fontcm48.d" \
"fonts\fontcm48b.d" \
"fonts\fontcm48i.d" \
"fonts\fontcmsc12.d" \
"fonts\fontcmsc14.d" \
"fonts\fontcmsc16.d" \
"fonts\fontcmsc18.d" \
"fonts\fontcmsc20.d" \
"fonts\fontcmsc22.d" \
"fonts\fontcmsc24.d" \
"fonts\fontcmsc26.d" \
"fonts\fontcmsc28.d" \
"fonts\fontcmsc30.d" \
"fonts\fontcmsc32.d" \
"fonts\fontcmsc34.d" \
"fonts\fontcmsc36.d" \
"fonts\fontcmsc38.d" \
"fonts\fontcmsc40.d" \
"fonts\fontcmsc42.d" \
"fonts\fontcmsc44.d" \
"fonts\fontcmsc46.d" \
"fonts\fontcmsc48.d" \
"fonts\fontcmss12.d" \
"fonts\fontcmss12b.d" \
"fonts\fontcmss12i.d" \
"fonts\fontcmss14.d" \
"fonts\fontcmss14b.d" \
"fonts\fontcmss14i.d" \
"fonts\fontcmss16.d" \
"fonts\fontcmss16b.d" \
"fonts\fontcmss16i.d" \
"fonts\fontcmss18.d" \
"fonts\fontcmss18b.d" \
"fonts\fontcmss18i.d" \
"fonts\fontcmss20.d" \
"fonts\fontcmss20b.d" \
"fonts\fontcmss20i.d" \
"fonts\fontcmss22.d" \
"fonts\fontcmss22b.d" \
"fonts\fontcmss22i.d" \
"fonts\fontcmss24.d" \
"fonts\fontcmss24b.d" \
"fonts\fontcmss24i.d" \
"fonts\fontcmss26.d" \
"fonts\fontcmss26b.d" \
"fonts\fontcmss26i.d" \
"fonts\fontcmss28.d" \
"fonts\fontcmss28b.d" \
"fonts\fontcmss28i.d" \
"fonts\fontcmss30.d" \
"fonts\fontcmss30b.d" \
"fonts\fontcmss30i.d" \
"fonts\fontcmss32.d" \
"fonts\fontcmss32b.d" \
"fonts\fontcmss32i.d" \
"fonts\fontcmss34.d" \
"fonts\fontcmss34b.d" \
"fonts\fontcmss34i.d" \
"fonts\fontcmss36.d" \
"fonts\fontcmss36b.d" \
"fonts\fontcmss36i.d" \
"fonts\fontcmss38.d" \
"fonts\fontcmss38b.d" \
"fonts\fontcmss38i.d" \
"fonts\fontcmss40.d" \
"fonts\fontcmss40b.d" \
"fonts\fontcmss40i.d" \
"fonts\fontcmss42.d" \
"fonts\fontcmss42b.d" \
"fonts\fontcmss42i.d" \
"fonts\fontcmss44.d" \
"fonts\fontcmss44b.d" \
"fonts\fontcmss44i.d" \
"fonts\fontcmss46.d" \
"fonts\fontcmss46b.d" \
"fonts\fontcmss46i.d" \
"fonts\fontcmss48.d" \
"fonts\fontcmss48b.d" \
"fonts\fontcmss48i.d" \
"fonts\fontcmtt12.d" \
"fonts\fontcmtt14.d" \
"fonts\fontcmtt16.d" \
"fonts\fontcmtt18.d" \
"fonts\fontcmtt20.d" \
"fonts\fontcmtt22.d" \
"fonts\fontcmtt24.d" \
"fonts\fontcmtt26.d" \
"fonts\fontcmtt28.d" \
"fonts\fontcmtt30.d" \
"fonts\fontcmtt32.d" \
"fonts\fontcmtt34.d" \
"fonts\fontcmtt36.d" \
"fonts\fontcmtt38.d" \
"fonts\fontcmtt40.d" \
"fonts\fontcmtt42.d" \
"fonts\fontcmtt44.d" \
"fonts\fontcmtt46.d" \
"fonts\fontcmtt48.d" \
"fonts\fontfixed6x8.d" 

C_SRCS__QUOTED += \
"../fonts/fontcm12.c" \
"../fonts/fontcm12b.c" \
"../fonts/fontcm12i.c" \
"../fonts/fontcm14.c" \
"../fonts/fontcm14b.c" \
"../fonts/fontcm14i.c" \
"../fonts/fontcm16.c" \
"../fonts/fontcm16b.c" \
"../fonts/fontcm16i.c" \
"../fonts/fontcm18.c" \
"../fonts/fontcm18b.c" \
"../fonts/fontcm18i.c" \
"../fonts/fontcm20.c" \
"../fonts/fontcm20b.c" \
"../fonts/fontcm20i.c" \
"../fonts/fontcm22.c" \
"../fonts/fontcm22b.c" \
"../fonts/fontcm22i.c" \
"../fonts/fontcm24.c" \
"../fonts/fontcm24b.c" \
"../fonts/fontcm24i.c" \
"../fonts/fontcm26.c" \
"../fonts/fontcm26b.c" \
"../fonts/fontcm26i.c" \
"../fonts/fontcm28.c" \
"../fonts/fontcm28b.c" \
"../fonts/fontcm28i.c" \
"../fonts/fontcm30.c" \
"../fonts/fontcm30b.c" \
"../fonts/fontcm30i.c" \
"../fonts/fontcm32.c" \
"../fonts/fontcm32b.c" \
"../fonts/fontcm32i.c" \
"../fonts/fontcm34.c" \
"../fonts/fontcm34b.c" \
"../fonts/fontcm34i.c" \
"../fonts/fontcm36.c" \
"../fonts/fontcm36b.c" \
"../fonts/fontcm36i.c" \
"../fonts/fontcm38.c" \
"../fonts/fontcm38b.c" \
"../fonts/fontcm38i.c" \
"../fonts/fontcm40.c" \
"../fonts/fontcm40b.c" \
"../fonts/fontcm40i.c" \
"../fonts/fontcm42.c" \
"../fonts/fontcm42b.c" \
"../fonts/fontcm42i.c" \
"../fonts/fontcm44.c" \
"../fonts/fontcm44b.c" \
"../fonts/fontcm44i.c" \
"../fonts/fontcm46.c" \
"../fonts/fontcm46b.c" \
"../fonts/fontcm46i.c" \
"../fonts/fontcm48.c" \
"../fonts/fontcm48b.c" \
"../fonts/fontcm48i.c" \
"../fonts/fontcmsc12.c" \
"../fonts/fontcmsc14.c" \
"../fonts/fontcmsc16.c" \
"../fonts/fontcmsc18.c" \
"../fonts/fontcmsc20.c" \
"../fonts/fontcmsc22.c" \
"../fonts/fontcmsc24.c" \
"../fonts/fontcmsc26.c" \
"../fonts/fontcmsc28.c" \
"../fonts/fontcmsc30.c" \
"../fonts/fontcmsc32.c" \
"../fonts/fontcmsc34.c" \
"../fonts/fontcmsc36.c" \
"../fonts/fontcmsc38.c" \
"../fonts/fontcmsc40.c" \
"../fonts/fontcmsc42.c" \
"../fonts/fontcmsc44.c" \
"../fonts/fontcmsc46.c" \
"../fonts/fontcmsc48.c" \
"../fonts/fontcmss12.c" \
"../fonts/fontcmss12b.c" \
"../fonts/fontcmss12i.c" \
"../fonts/fontcmss14.c" \
"../fonts/fontcmss14b.c" \
"../fonts/fontcmss14i.c" \
"../fonts/fontcmss16.c" \
"../fonts/fontcmss16b.c" \
"../fonts/fontcmss16i.c" \
"../fonts/fontcmss18.c" \
"../fonts/fontcmss18b.c" \
"../fonts/fontcmss18i.c" \
"../fonts/fontcmss20.c" \
"../fonts/fontcmss20b.c" \
"../fonts/fontcmss20i.c" \
"../fonts/fontcmss22.c" \
"../fonts/fontcmss22b.c" \
"../fonts/fontcmss22i.c" \
"../fonts/fontcmss24.c" \
"../fonts/fontcmss24b.c" \
"../fonts/fontcmss24i.c" \
"../fonts/fontcmss26.c" \
"../fonts/fontcmss26b.c" \
"../fonts/fontcmss26i.c" \
"../fonts/fontcmss28.c" \
"../fonts/fontcmss28b.c" \
"../fonts/fontcmss28i.c" \
"../fonts/fontcmss30.c" \
"../fonts/fontcmss30b.c" \
"../fonts/fontcmss30i.c" \
"../fonts/fontcmss32.c" \
"../fonts/fontcmss32b.c" \
"../fonts/fontcmss32i.c" \
"../fonts/fontcmss34.c" \
"../fonts/fontcmss34b.c" \
"../fonts/fontcmss34i.c" \
"../fonts/fontcmss36.c" \
"../fonts/fontcmss36b.c" \
"../fonts/fontcmss36i.c" \
"../fonts/fontcmss38.c" \
"../fonts/fontcmss38b.c" \
"../fonts/fontcmss38i.c" \
"../fonts/fontcmss40.c" \
"../fonts/fontcmss40b.c" \
"../fonts/fontcmss40i.c" \
"../fonts/fontcmss42.c" \
"../fonts/fontcmss42b.c" \
"../fonts/fontcmss42i.c" \
"../fonts/fontcmss44.c" \
"../fonts/fontcmss44b.c" \
"../fonts/fontcmss44i.c" \
"../fonts/fontcmss46.c" \
"../fonts/fontcmss46b.c" \
"../fonts/fontcmss46i.c" \
"../fonts/fontcmss48.c" \
"../fonts/fontcmss48b.c" \
"../fonts/fontcmss48i.c" \
"../fonts/fontcmtt12.c" \
"../fonts/fontcmtt14.c" \
"../fonts/fontcmtt16.c" \
"../fonts/fontcmtt18.c" \
"../fonts/fontcmtt20.c" \
"../fonts/fontcmtt22.c" \
"../fonts/fontcmtt24.c" \
"../fonts/fontcmtt26.c" \
"../fonts/fontcmtt28.c" \
"../fonts/fontcmtt30.c" \
"../fonts/fontcmtt32.c" \
"../fonts/fontcmtt34.c" \
"../fonts/fontcmtt36.c" \
"../fonts/fontcmtt38.c" \
"../fonts/fontcmtt40.c" \
"../fonts/fontcmtt42.c" \
"../fonts/fontcmtt44.c" \
"../fonts/fontcmtt46.c" \
"../fonts/fontcmtt48.c" \
"../fonts/fontfixed6x8.c" 


